# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/170KNdRbU6788vg0FeSZDy4Rqq-zRf-C4
"""

# Import module untuk menggambar grafik
import matplotlib.pyplot as plt
import numpy as np

# Fungsi untuk sub sistem
def pantai_a():
  print("--------------------------------------------")
  # Input data monitoring pada pantai A
  a = int(input("Masukkan temperature (Celcius) : "))
  b = int(input("Masukkan kelembaban (%) : "))
  c = int(input("Masukkan kadar PM ( µgram/m3) : "))

  #Membuat plot
  x = np.array(["temperature","kelembaban","kadar"])
  y= np.array([a,b,c])

  # Judul diagram
  plt.title("Pantai A")
  # Memunculkan diagram
  plt.bar(x,y)
  plt.show()

  # Validasi input data 
  if (a <= 29) and (a >= 26) and (b <= 65) and (b >= 45) and (c<=15) and (c > 0):
    print("Status : Normal")

  elif (a < 26):
    print("Alert")
    print("Status data (Temperature) : Rendah")
    if (b < 45):
      print("Status data (Kelembaban) : Rendah")
      if (c < 0):
        print("Status data (Kadar) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (b < 45):
    print("Alert")
    print("Status data (Kelembaban) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (c < 0):
    print("Alert")
    print("Status data (Kadar) : Rendah")

  elif (a > 29):
    print("Alert")
    print("Status data (Temperature) : Tinggi")
    if(b > 65):
      print("Status data (Kelembaban) : Tinggi")
      if(c > 15):
        print("Status data (Kadar) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (b > 65):
    print("Status data (Kelembaban) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (c > 15):
    print("Status data (Kadar) : Tinggi")
    print("Alarm  : ON")

def pantai_b():
  # Input data monitoring pada pantai B
  print("--------------------------------------------")
  a = int(input("Masukkan temperature (Celcius) : "))
  b = int(input("Masukkan kelembaban (%) : "))
  c = int(input("Masukkan kadar PM ( µgram/m3) : "))

  #Membuat plot
  x = np.array(["temperature","kelembaban","kadar"])
  y= np.array([a,b,c])

  # Judul diagram
  plt.title("Pantai B")
  # Memunculkan diagram
  plt.bar(x,y)
  plt.show()

  # Validasi input data 
  if (a <= 29) and (a >= 26) and (b <= 65) and (b >= 45) and (c<=15) and (c > 0):
    print("Status : Normal")

  elif (a < 26):
    print("Alert")
    print("Status data (Temperature) : Rendah")
    if (b < 45):
      print("Status data (Kelembaban) : Rendah")
      if (c < 0):
        print("Status data (Kadar) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (b < 45):
    print("Alert")
    print("Status data (Kelembaban) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (c < 0):
    print("Alert")
    print("Status data (Kadar) : Rendah")

  elif (a > 29):
    print("Alert")
    print("Status data (Temperature) : Tinggi")
    if(b > 65):
      print("Status data (Kelembaban) : Tinggi")
      if(c > 15):
        print("Status data (Kadar) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (b > 65):
    print("Status data (Kelembaban) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (c > 15):
    print("Status data (Kadar) : Tinggi")
    print("Alarm  : ON")

def pantai_c():
  print("--------------------------------------------")
  # Input data monitoring pada pantai B
  a = int(input("Masukkan temperature (Celcius) : "))
  b = int(input("Masukkan kelembaban (%) : "))
  c = int(input("Masukkan kadar PM ( µgram/m3) : "))

  #Membuat plot
  x = np.array(["temperature","kelembaban","kadar"])
  y= np.array([a,b,c])

  # Judul diagram
  plt.title("Pantai C")
  # Memunculkan diagram
  plt.bar(x,y)
  plt.show()

  # Validasi input data 
  if (a <= 29) and (a >= 26) and (b <= 65) and (b >= 45) and (c<=15) and (c > 0):
    print("Status : Normal")

  elif (a < 26):
    print("Alert")
    print("Status data (Temperature) : Rendah")
    if (b < 45):
      print("Status data (Kelembaban) : Rendah")
      if (c < 0):
        print("Status data (Kadar) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (b < 45):
    print("Alert")
    print("Status data (Kelembaban) : Rendah")
    if (c < 0):
      print("Status data (Kadar) : Rendah")
    print("Alarm : ON")

  elif (c < 0):
    print("Alert")
    print("Status data (Kadar) : Rendah")

  elif (a > 29):
    print("Alert")
    print("Status data (Temperature) : Tinggi")
    if(b > 65):
      print("Status data (Kelembaban) : Tinggi")
      if(c > 15):
        print("Status data (Kadar) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (b > 65):
    print("Status data (Kelembaban) : Tinggi")
    if(c > 15):
      print("Status data (Kadar) : Tinggi")
    print("Alarm : ON")

  elif (c > 15):
    print("Status data (Kadar) : Tinggi")
    print("Alarm  : ON")

pantai_a()
pantai_b()
pantai_c()